DELIMITER $$
CREATE DEFINER = `root`@`localhost` EVENT `BI`.`EVNT_NGHT_CHCK`
ON SCHEDULE EVERY 1 DAY STARTS '2015-06-03 04:00:00'
ON COMPLETION PRESERVE
ENABLE
DO
BEGIN
	DECLARE `_rollback` BOOL DEFAULT 0;
	DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET `_rollback` = 1;
	START TRANSACTION;

	UPDATE RoomTran SET DPST_RMN = DPST_RMN - RM_AVE_PRCE 
		WHERE FILLED = 'F' AND TMP_PLAN_ID IS NULL;

	INSERT INTO RoomAcct (RM_TRAN_ID, RM_PAY_AMNT, BILL_TSTMP, ORGN_ACCT_ID, RM_PAY_METHOD, EMP_ID, TKN_RM_TRAN_ID, FILLED, RMRK)
		SELECT RM_TRAN_ID, RM_AVE_PRCE, LOCALTIMESTAMP(), NULL, NULL, NULL, IF(CONN_RM_TRAN_ID IS NULL, RM_TRAN_ID, CONN_RM_TRAN_ID), 'F', '夜核房费'
		FROM RoomTran 
		WHERE FILLED = 'F' AND TMP_PLAN_ID IS NULL;

	IF `_rollback` THEN
			ROLLBACK;
		ELSE
			COMMIT;
		END IF;
END $$
DELIMITER ;

